# Site settings
course_name: Machine learning with kernel methods
course_description: ""
course_semester: "Spring 2025"

baseurl: "/course-page" # the subpath of your site, e.g. /blog/
url: "https://mva-kernel-methods.github.io/" # the base hostname & protocol for your site

schoolname: "IASD/MVA/MASH"
schoolurl: "https://dauphine.psl.eu/en/training/masters-degrees/computer-science/m2-artificial-intelligence-systems-data"


twitter_username: username 

address: |
    IASD/MVA/MASH
    Dauphine, PSL University/ENS Paris Saclay

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
